title: Learn Metal
description: A modern, open-source tutorial site designed to teach Apple’s Metal graphics API
theme: just-the-docs

permalink: pretty

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: "k"

enable_copy_code_button: true

mermaid:
  version: "9.1.6"

heading_anchors: true

aux_links:
  "Learn Metal on Github":
    - "https://github.com/theboredprog/learnmetal/"

aux_links_new_tab: false

nav_enabled: true

nav_sort: case_sensitive

nav_external_links:
  - title: Learn Metal on Github
    url: https://github.com/theboredprog/learnmetal/

nav_error_report: true

liquid:
  error_mode: strict
  strict_filters: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2025 Gabriele Vierti. Distributed by an <a href="https://github.com/theboredprog/learnmetal/blob/main/LICENSE">MIT license.</a>'

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

color_scheme: nil

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
